### ISSUE TITLE
Persistent login

### ISSUE THREAD

**Issue by mpor** [mohith7548/Firebase-Phone-Auth-Demo#1]
Sorry if it's too much of a basic question (i am a newbie on Flutter), but my problem is that once a user goes through the login and enters the app, once the app gets killed and restarted, the user is facing the login again.

How to avoid this?

Thanks

**Comment by edusun** [comment]
save user state.

**Comment by mohith7548** [comment]
This will help you. It's answered here: https://stackoverflow.com/questions/46213159/in-flutter-how-to-get-current-user-logged-in-from-the-cache-maintained-by-fireba/50083848#50083848

**Comment by mpor** [comment]
Thanks to all, meanwhile I had solved through the help of
https://stackoverflow.com/questions/54469191/persist-user-auth-flutter-firebase
.

Best
Mirco



Il giorno dom 5 apr 2020 alle ore 13:58 Kune Mohith <
notifications@github.com> ha scritto:
